run:
  timeout: 10m

linters:
  enable:
  - bodyclose
  - gocognit
  - gocyclo
  - gofmt
  - goimports
  - golint
  - goprintffuncname
  - gosec
  - govet
  - lll
  - misspell
  - nakedret
  - staticcheck
  - unconvert
  - unparam

linters-settings:
  misspell:
    ignore-words:
    - clas
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false
  govet:
    exclude:

issues:
  exclude:
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
