before:
  hooks:
  - go mod download
  - go generate ./...
  - make generate
builds:
- env:
  - CGO_ENABLED=0
  goarch:
  - amd64
  goos:
  - linux
  - darwin
  ldflags:
  - -s
  - -w
  - -X github.com/projectcontour/integration-tester/pkg/version.Version={{ .Env.VERSION }}
  - -X github.com/projectcontour/integration-tester/pkg/version.Sha={{ .Env.SHA }}
  - -X github.com/projectcontour/integration-tester/pkg/version.BuildDate={{ .Date }}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
